import { Question, RecruitmentSite, PersonalityResult, TypeCompatibility } from './mbti-types';

// 5段階評価対応、各指標(EI, SN, TF, JP)につき7-8問、合計30問
export const QUESTIONS: Question[] = [
  // --- E vs I (興味の方向: 1-8) ---
  {
    id: 1,
    text: "申し送りの時間がやってきました。あなたは？",
    dimension: 'EI',
    optionA: { text: "同僚と雑談しながら情報交換するのが好き", type: 'E' },
    optionB: { text: "必要な情報だけを静かに確認したい", type: 'I' },
  },
  {
    id: 2,
    text: "忙しい夜勤明け。同僚に食事に誘われました。",
    dimension: 'EI',
    optionA: { text: "行く！喋ってストレス発散したい", type: 'E' },
    optionB: { text: "断るかも。早く帰って一人で充電したい", type: 'I' },
  },
  {
    id: 3,
    text: "新しい病棟や部署に異動しました。まずどうする？",
    dimension: 'EI',
    optionA: { text: "自分から積極的に挨拶して回る", type: 'E' },
    optionB: { text: "様子を見ながら、話しかけられるのを待つ", type: 'I' },
  },
  {
    id: 4,
    text: "考えをまとめるときは？",
    dimension: 'EI',
    optionA: { text: "誰かに話しながら整理する", type: 'E' },
    optionB: { text: "一人でじっくり頭の中で考える", type: 'I' },
  },
  {
    id: 5,
    text: "休憩時間の過ごし方は？",
    dimension: 'EI',
    optionA: { text: "スタッフルームで同僚とおしゃべり", type: 'E' },
    optionB: { text: "一人でスマホを見たり、静かに過ごしたい", type: 'I' },
  },
  {
    id: 6,
    text: "勉強会や研修会で新しい人と一緒になったとき",
    dimension: 'EI',
    optionA: { text: "積極的に話しかけて交流を楽しむ", type: 'E' },
    optionB: { text: "必要なとき以外は静かに過ごしたい", type: 'I' },
  },
  {
    id: 7,
    text: "仕事で困ったことがあったとき",
    dimension: 'EI',
    optionA: { text: "すぐに誰かに相談して解決したい", type: 'E' },
    optionB: { text: "まず自分で調べて考えてから相談する", type: 'I' },
  },
  {
    id: 8,
    text: "長期休暇の過ごし方は？",
    dimension: 'EI',
    optionA: { text: "友人や家族とアクティブに過ごす", type: 'E' },
    optionB: { text: "家でゆっくり、自分の時間を楽しむ", type: 'I' },
  },

  // --- S vs N (ものの見方: 9-16) ---
  {
    id: 9,
    text: "急変対応中、どのように動くことが多い？",
    dimension: 'SN',
    optionA: { text: "目の前のバイタルや処置に集中して確実に行う", type: 'S' },
    optionB: { text: "「なぜ急変したか」全体像や次の展開を予測する", type: 'N' },
  },
  {
    id: 10,
    text: "新しい医療機器が導入されました。",
    dimension: 'SN',
    optionA: { text: "まずはマニュアル通り、具体的な操作手順を覚える", type: 'S' },
    optionB: { text: "その機器の仕組みや、導入された意義を理解したい", type: 'N' },
  },
  {
    id: 11,
    text: "患者さんの情報を取るとき、重視するのは？",
    dimension: 'SN',
    optionA: { text: "検査データや数値などの事実情報", type: 'S' },
    optionB: { text: "患者さんの表情や、その場の雰囲気などの印象", type: 'N' },
  },
  {
    id: 12,
    text: "看護観について議論になりました。",
    dimension: 'SN',
    optionA: { text: "「今、実際に何ができるか」という現実的な話が好き", type: 'S' },
    optionB: { text: "「将来、どうあるべきか」という理想の話が好き", type: 'N' },
  },
  {
    id: 13,
    text: "キャリアについて考えるとき",
    dimension: 'SN',
    optionA: { text: "今の経験やスキルを着実に積み上げていきたい", type: 'S' },
    optionB: { text: "将来の可能性や新しい分野への挑戦を考える", type: 'N' },
  },
  {
    id: 14,
    text: "患者さんへの説明の仕方は？",
    dimension: 'SN',
    optionA: { text: "具体的な手順や数値を使って分かりやすく", type: 'S' },
    optionB: { text: "全体像やイメージを伝えてから詳細を説明", type: 'N' },
  },
  {
    id: 15,
    text: "業務改善の提案をするとき",
    dimension: 'SN',
    optionA: { text: "実績やデータに基づいた具体的な提案をする", type: 'S' },
    optionB: { text: "新しいアイデアや可能性を重視して提案する", type: 'N' },
  },

  // --- T vs F (判断の仕方: 16-23) ---
  {
    id: 16,
    text: "患者さんからの理不尽なクレーム。どう対応する？",
    dimension: 'TF',
    optionA: { text: "病院のルールと事実に基づいて論理的に説明する", type: 'T' },
    optionB: { text: "まずは患者さんの不安や辛い気持ちに寄り添う", type: 'F' },
  },
  {
    id: 17,
    text: "チームリーダーを任されました。意識することは？",
    dimension: 'TF',
    optionA: { text: "業務効率とタスクの公平な配分", type: 'T' },
    optionB: { text: "メンバーの人間関係とモチベーション維持", type: 'F' },
  },
  {
    id: 18,
    text: "後輩がミスをしました。どう指導する？",
    dimension: 'TF',
    optionA: { text: "原因と対策を論理的に分析させる", type: 'T' },
    optionB: { text: "落ち込んでいる気持ちに配慮しながら励ます", type: 'F' },
  },
  {
    id: 19,
    text: "多職種カンファレンスで意見が割れました。",
    dimension: 'TF',
    optionA: { text: "エビデンスに基づき、最も合理的な案を推す", type: 'T' },
    optionB: { text: "全員が納得できるよう、調和を重視して調整する", type: 'F' },
  },
  {
    id: 20,
    text: "同僚から仕事の相談を受けたとき",
    dimension: 'TF',
    optionA: { text: "問題解決のための具体的なアドバイスをする", type: 'T' },
    optionB: { text: "まず話を聞いて、気持ちを受け止める", type: 'F' },
  },
  {
    id: 21,
    text: "難しい判断を迫られたとき",
    dimension: 'TF',
    optionA: { text: "論理的に考えて最善の選択をする", type: 'T' },
    optionB: { text: "関係者の気持ちを考慮して決める", type: 'F' },
  },
  {
    id: 22,
    text: "患者さんの退院支援について",
    dimension: 'TF',
    optionA: { text: "制度や手続きを正確に説明することを重視", type: 'T' },
    optionB: { text: "患者さんや家族の不安に寄り添うことを重視", type: 'F' },
  },
  {
    id: 23,
    text: "フィードバックを受けるとき",
    dimension: 'TF',
    optionA: { text: "客観的な評価と改善点を知りたい", type: 'T' },
    optionB: { text: "良かった点も含めて励ましてほしい", type: 'F' },
  },

  // --- J vs P (外界への接し方: 24-30) ---
  {
    id: 24,
    text: "休日の予定の立て方は？",
    dimension: 'JP',
    optionA: { text: "事前にしっかり計画を立てて、その通り動きたい", type: 'J' },
    optionB: { text: "その日の気分で決めたい、変更も柔軟に受け入れる", type: 'P' },
  },
  {
    id: 25,
    text: "予測外の緊急入院が入りました。",
    dimension: 'JP',
    optionA: { text: "ペースが乱れて少しストレスを感じる", type: 'J' },
    optionB: { text: "バタバタする状況にスイッチが入る", type: 'P' },
  },
  {
    id: 26,
    text: "業務の進め方について。",
    dimension: 'JP',
    optionA: { text: "タイムスケジュール通りにきっちり終わらせたい", type: 'J' },
    optionB: { text: "状況に合わせて柔軟に対応したい、多少の遅れは気にしない", type: 'P' },
  },
  {
    id: 27,
    text: "看護計画を立てるとき",
    dimension: 'JP',
    optionA: { text: "詳細な計画を立て、その通りに進めたい", type: 'J' },
    optionB: { text: "大まかな方向性だけ決め、状況に応じて調整", type: 'P' },
  },
  {
    id: 28,
    text: "デスク周りや持ち物の管理は？",
    dimension: 'JP',
    optionA: { text: "整理整頓されていないと落ち着かない", type: 'J' },
    optionB: { text: "多少散らかっていても気にならない、探せば見つかる", type: 'P' },
  },
  {
    id: 29,
    text: "旅行の計画を立てるとき",
    dimension: 'JP',
    optionA: { text: "行き先や時間をしっかり決めてから出発", type: 'J' },
    optionB: { text: "大まかな目的地だけ決めて、あとは現地で決める", type: 'P' },
  },
  {
    id: 30,
    text: "締め切りがある仕事への取り組み方は？",
    dimension: 'JP',
    optionA: { text: "早めに着手して、余裕を持って終わらせる", type: 'J' },
    optionB: { text: "締め切り間際に集中力が高まってこなす", type: 'P' },
  },
];

export const PERSONALITY_TYPES: Record<string, PersonalityResult> = {
  ISTJ: {
    type: "ISTJ",
    title: "責任感の強い管理者ナース",
    description: "ルールと秩序を重んじ、正確な看護技術を提供します。ミスが許されない現場で非常に頼りにされる存在です。",
    strengths: ["正確性", "責任感", "組織的"],
    workStyle: "手順が決まっているルーチンワークや、急性期でもプロトコルが明確な場所が得意。",
    characterImage: "/images/mbti/ISTJ.png",
  },
  ISFJ: {
    type: "ISFJ",
    title: "心優しき擁護者ナース",
    description: "患者さん一人ひとりに寄り添い、献身的なケアを行います。チームの和を大切にする、まさに「白衣の天使」タイプ。",
    strengths: ["共感力", "忍耐強さ", "細やかな気配り"],
    workStyle: "慢性期病棟やクリニックなど、患者さんとじっくり関われる環境。",
    characterImage: "/images/mbti/ISFJ.png",
  },
  INFJ: {
    type: "INFJ",
    title: "洞察力のある提唱者ナース",
    description: "患者さんの言葉にならない訴えを直感的に理解します。理想の看護を追い求める強い信念を持っています。",
    strengths: ["洞察力", "創造性", "強い信念"],
    workStyle: "緩和ケアや精神科など、心のケアが重視される専門的な領域。",
    characterImage: "/images/mbti/INFJ.png",
  },
  INTJ: {
    type: "INTJ",
    title: "戦略的な建築家ナース",
    description: "常に業務改善を考え、効率的なシステムを構築しようとします。高度な知識を要する認定・専門看護師向き。",
    strengths: ["分析力", "長期的視点", "独立心"],
    workStyle: "大学病院の研究部門や、高度救命救急、手術室。",
    characterImage: "/images/mbti/INTJ.png",
  },
  ISTP: {
    type: "ISTP",
    title: "冷静な巨匠ナース",
    description: "緊急時でも動じず、淡々と処置をこなします。機器の扱いや手技が得意で、現場でのトラブルシューティングに強い。",
    strengths: ["適応力", "冷静沈着", "技術力"],
    workStyle: "救急外来(ER)、ICU、オペ室などの実動部隊。",
    characterImage: "/images/mbti/ISTP.png",
  },
  ISFP: {
    type: "ISFP",
    title: "温厚な冒険家ナース",
    description: "控えめですが、患者さんの個別性を尊重した温かいケアをします。美意識が高く、環境整備なども得意。",
    strengths: ["観察力", "柔軟性", "優しさ"],
    workStyle: "訪問看護、小児科、美容クリニック。",
    characterImage: "/images/mbti/ISFP.png",
  },
  INFP: {
    type: "INFP",
    title: "情熱的な仲介者ナース",
    description: "自分の価値観を大切にし、患者さんの人生そのものを尊重します。マニュアルよりも心を重視するタイプ。",
    strengths: ["理想主義", "傾聴力", "適応性"],
    workStyle: "ホスピス、心療内科、訪問看護。",
    characterImage: "/images/mbti/INFP.png",
  },
  INTP: {
    type: "INTP",
    title: "論理的な学者ナース",
    description: "「なぜそうなるのか」を深く理解したいタイプ。エビデンスに基づいた看護や、新しい治療法への関心が高い。",
    strengths: ["論理的思考", "客観性", "知的好奇心"],
    workStyle: "臨床研究コーディネーター(CRC)、大学病院。",
    characterImage: "/images/mbti/INTP.png",
  },
  ESTP: {
    type: "ESTP",
    title: "活動的な起業家ナース",
    description: "考えるよりまず行動。スピード感が求められる現場で輝きます。リスクを恐れず、困難な状況を楽しめる強さがあります。",
    strengths: ["行動力", "機転", "エネルギー"],
    workStyle: "ドクターヘリ、救命救急、災害医療。",
    characterImage: "/images/mbti/ESTP.png",
  },
  ESFP: {
    type: "ESFP",
    title: "陽気なエンターテイナーナース",
    description: "病棟のムードメーカー。患者さんを笑顔にする力があります。チームワークを重視し、現場を明るくします。",
    strengths: ["社交性", "楽観性", "実践的"],
    workStyle: "小児科、リハビリテーション病棟、デイサービス。",
    characterImage: "/images/mbti/ESFP.png",
  },
  ENFP: {
    type: "ENFP",
    title: "広報運動家ナース",
    description: "好奇心旺盛で、新しいことへの挑戦が大好き。患者さんともすぐに打ち解け、精神的なサポートが得意です。",
    strengths: ["熱意", "コミュニケーション", "発想力"],
    workStyle: "地域連携室、訪問看護、健康教育・保健師。",
    characterImage: "/images/mbti/ENFP.png",
  },
  ENTP: {
    type: "ENTP",
    title: "議論好きな討論者ナース",
    description: "常識にとらわれず、新しい看護のあり方を模索します。変化の多い環境や、複雑な問題を解決するのが得意。",
    strengths: ["知識欲", "多角的な視点", "革新性"],
    workStyle: "看護管理、医療コンサルタント、新規立ち上げクリニック。",
    characterImage: "/images/mbti/ENTP.png",
  },
  ESTJ: {
    type: "ESTJ",
    title: "厳格な幹部ナース",
    description: "組織のルールを守り、効率的に業務を回します。リーダーシップがあり、新人指導や管理業務に向いています。",
    strengths: ["統率力", "秩序", "決断力"],
    workStyle: "病棟師長、看護部長、急性期病棟のリーダー。",
    characterImage: "/images/mbti/ESTJ.png",
  },
  ESFJ: {
    type: "ESFJ",
    title: "社交的な領事官ナース",
    description: "困っている人を放っておけない、世話焼きタイプ。チームの調和を保ち、患者さんや家族からの信頼も厚いです。",
    strengths: ["協調性", "忠誠心", "実務能力"],
    workStyle: "一般病棟、外来、透析室。",
    characterImage: "/images/mbti/ESFJ.png",
  },
  ENFJ: {
    type: "ENFJ",
    title: "カリスマ的な主人公ナース",
    description: "人々を励まし、成長させることに喜びを感じます。高い共感力とリーダーシップで、理想的なチームを作ります。",
    strengths: ["カリスマ性", "共感力", "指導力"],
    workStyle: "教育担当、看護学校教員、精神科リエゾン。",
    characterImage: "/images/mbti/ENFJ.png",
  },
  ENTJ: {
    type: "ENTJ",
    title: "主導権を握る指揮官ナース",
    description: "長期的ビジョンを持ち、組織を牽引します。感情に流されず、合理的な判断で最善の結果を出そうとします。",
    strengths: ["戦略的思考", "自信", "意志の強さ"],
    workStyle: "病院経営、看護管理者、起業。",
    characterImage: "/images/mbti/ENTJ.png",
  },
};

export const RECRUITMENT_SITES: RecruitmentSite[] = [
  {
    name: "看護roo!",
    description: "利用者満足度が高く、手厚いサポートが魅力。初めての転職や相談重視の方に。",
    url: "https://919.resistance1.com/clk.php?sid=1537&iid=31",
    color: "bg-pink-500",
    tags: ["満足度高い", "徹底サポート", "内部情報"],
    recommendedFor: ["ISFJ", "ESFJ", "INFJ", "ENFJ", "INFP", "ISFP", "ESFP", "ENFP", "ISTJ", "ESTJ", "ENTJ", "INTJ"],
  },
  {
    name: "レバウェル看護",
    description: "LINEで気軽に相談可能。職場のリアルな情報が詳しく、効率的に探したい方に。",
    url: "https://px.a8.net/svt/ejp?a8mat=3T0G8N+5E3BZM+2JK4+62U37",
    color: "bg-teal-500",
    tags: ["LINE相談", "情報量豊富", "スピード"],
    recommendedFor: ["ISTP", "INTP", "ENTP", "ENFP", "ESFP", "ESTP", "ISFP", "ENTJ", "INTJ", "INFJ", "ISTJ", "ESTJ"],
  },
];

// タイプ別相性マトリクス（看護師チーム視点）
export const TYPE_COMPATIBILITY: Record<string, Record<string, TypeCompatibility>> = {
  // 各タイプとの相性を定義（簡略化版、主要な組み合わせのみ）
  ISTJ: {
    ISTJ: { type: 'ISTJ', compatibility: 'good', description: '同じ価値観で安定した連携', workTip: 'ルーティンを共有し、互いの担当を明確に' },
    ISFJ: { type: 'ISFJ', compatibility: 'excellent', description: '最高の相性、互いを補完', workTip: '感情面のサポートを任せ、あなたは実務を' },
    ESTJ: { type: 'ESTJ', compatibility: 'excellent', description: '効率的で頼れるパートナー', workTip: 'リーダーシップを分担して最強チームに' },
    ESFJ: { type: 'ESFJ', compatibility: 'good', description: '安定感のある協力関係', workTip: '人間関係の調整は相手に任せて' },
    ENFP: { type: 'ENFP', compatibility: 'challenging', description: '異なる視点が刺激的だが衝突も', workTip: 'アイデアを受け入れる余裕を持とう' },
    INFP: { type: 'INFP', compatibility: 'neutral', description: '互いを理解するには時間が必要', workTip: '相手のペースを尊重して' },
    default: { type: '', compatibility: 'neutral', description: '互いを理解し合えば良い関係に', workTip: 'コミュニケーションを大切に' },
  },
  ISFJ: {
    ISFJ: { type: 'ISFJ', compatibility: 'good', description: '優しさが共鳴する関係', workTip: '互いに気を遣いすぎず本音で' },
    ISTJ: { type: 'ISTJ', compatibility: 'excellent', description: '最高の相性、信頼で結ばれる', workTip: '感情面のサポートを担当して' },
    ESFJ: { type: 'ESFJ', compatibility: 'excellent', description: '患者ケアで最強コンビ', workTip: '表舞台は相手に任せてサポート役を' },
    ENFJ: { type: 'ENFJ', compatibility: 'good', description: '温かいチームを作れる', workTip: 'リーダーを支える副リーダーとして' },
    ENTP: { type: 'ENTP', compatibility: 'challenging', description: '変化の速さについていくのが大変', workTip: '必要な変化だけ受け入れて' },
    default: { type: '', compatibility: 'neutral', description: 'あなたの優しさは誰とでも調和できる', workTip: '自分の意見も大切に' },
  },
  INFJ: {
    INFJ: { type: 'INFJ', compatibility: 'good', description: '深い理解で繋がれる', workTip: '言葉にしなくても通じる関係' },
    ENFJ: { type: 'ENFJ', compatibility: 'excellent', description: '理想を共有できるパートナー', workTip: '表現力のある相手に発信を任せて' },
    INFP: { type: 'INFP', compatibility: 'excellent', description: '価値観を共有、心地よい関係', workTip: '互いの内面を大切にする時間を' },
    INTJ: { type: 'INTJ', compatibility: 'good', description: '戦略的に協力できる', workTip: '論理と直感を組み合わせて' },
    ESTP: { type: 'ESTP', compatibility: 'challenging', description: '行動力は魅力だが価値観の違い', workTip: '現場での強さを認めよう' },
    default: { type: '', compatibility: 'neutral', description: '深い洞察力で相手を理解できる', workTip: '直感を信じて関わって' },
  },
  INTJ: {
    INTJ: { type: 'INTJ', compatibility: 'good', description: '互いの能力を認め合う', workTip: '競争より協力で最高の結果を' },
    ENTJ: { type: 'ENTJ', compatibility: 'excellent', description: '戦略的パートナー', workTip: '実行力のある相手とビジョンを形に' },
    INTP: { type: 'INTP', compatibility: 'excellent', description: '知的探求を共にできる', workTip: '議論を楽しみつつ結論を出そう' },
    INFJ: { type: 'INFJ', compatibility: 'good', description: '直感を共有できる', workTip: '感情面のサポートを学ぼう' },
    ESFP: { type: 'ESFP', compatibility: 'challenging', description: '真逆だが学びも多い', workTip: '現場での即興力を認めよう' },
    default: { type: '', compatibility: 'neutral', description: '戦略的視点で協力関係を築ける', workTip: 'コミュニケーションを明確に' },
  },
  ISTP: {
    ISTP: { type: 'ISTP', compatibility: 'good', description: '言葉少なくても通じる', workTip: '互いの空間を尊重して' },
    ESTP: { type: 'ESTP', compatibility: 'excellent', description: '実践的で頼れるコンビ', workTip: '急変対応では最強チーム' },
    ISTJ: { type: 'ISTJ', compatibility: 'good', description: '実務的な協力ができる', workTip: 'ルールの範囲内で柔軟に' },
    ENFJ: { type: 'ENFJ', compatibility: 'challenging', description: '感情表現の違いで誤解も', workTip: '行動で誠意を示そう' },
    default: { type: '', compatibility: 'neutral', description: '実践的なスキルで貢献できる', workTip: '言葉で伝える努力も大切' },
  },
  ISFP: {
    ISFP: { type: 'ISFP', compatibility: 'good', description: '穏やかで心地よい関係', workTip: '互いの感性を大切に' },
    ESFP: { type: 'ESFP', compatibility: 'excellent', description: '楽しく協力できる', workTip: '明るさを活かしてチームを盛り上げて' },
    ISFJ: { type: 'ISFJ', compatibility: 'good', description: '優しさで繋がる', workTip: '患者ケアで力を発揮' },
    ENTJ: { type: 'ENTJ', compatibility: 'challenging', description: 'ペースの違いにストレスも', workTip: '自分のペースも主張しよう' },
    default: { type: '', compatibility: 'neutral', description: '柔軟性で様々な人と協力できる', workTip: '自分の意見も表現しよう' },
  },
  INFP: {
    INFP: { type: 'INFP', compatibility: 'good', description: '価値観を深く共有', workTip: '理想を語り合える仲間' },
    INFJ: { type: 'INFJ', compatibility: 'excellent', description: '魂の友になれる', workTip: '互いの内面を尊重して' },
    ENFP: { type: 'ENFP', compatibility: 'excellent', description: '創造性が相乗効果', workTip: 'アイデアを形にする協力を' },
    ESTJ: { type: 'ESTJ', compatibility: 'challenging', description: '現実主義との衝突', workTip: '相手の効率重視を理解しよう' },
    default: { type: '', compatibility: 'neutral', description: '共感力で多くの人と繋がれる', workTip: '理想と現実のバランスを' },
  },
  INTP: {
    INTP: { type: 'INTP', compatibility: 'good', description: '知的な議論が楽しい', workTip: '結論を出すことも意識して' },
    INTJ: { type: 'INTJ', compatibility: 'excellent', description: '論理的パートナー', workTip: '戦略を立てて実行へ' },
    ENTP: { type: 'ENTP', compatibility: 'excellent', description: 'アイデアの応酬', workTip: '議論を建設的に活かそう' },
    ESFJ: { type: 'ESFJ', compatibility: 'challenging', description: '感情表現の違い', workTip: '相手の気遣いに感謝を伝えて' },
    default: { type: '', compatibility: 'neutral', description: '分析力でチームに貢献', workTip: '感情面のケアも忘れずに' },
  },
  ESTP: {
    ESTP: { type: 'ESTP', compatibility: 'good', description: 'エネルギッシュなコンビ', workTip: '競争より協力で成果を' },
    ISTP: { type: 'ISTP', compatibility: 'excellent', description: '実践的な最強タッグ', workTip: '急変対応では頼りになる' },
    ESTJ: { type: 'ESTJ', compatibility: 'good', description: '行動力で協力', workTip: 'ルールの範囲で柔軟に' },
    INFJ: { type: 'INFJ', compatibility: 'challenging', description: '価値観の違いに注意', workTip: '相手の深い洞察を尊重しよう' },
    default: { type: '', compatibility: 'neutral', description: '行動力でチームを牽引', workTip: '周囲の意見も聞こう' },
  },
  ESFP: {
    ESFP: { type: 'ESFP', compatibility: 'good', description: '楽しさが倍増', workTip: '仕事もしっかりバランスを' },
    ISFP: { type: 'ISFP', compatibility: 'excellent', description: '感性が響き合う', workTip: '患者さんを笑顔にできる' },
    ESFJ: { type: 'ESFJ', compatibility: 'good', description: '明るいチームを作れる', workTip: '計画性は相手に任せて' },
    INTJ: { type: 'INTJ', compatibility: 'challenging', description: '真逆ゆえの学びも', workTip: '戦略的視点を学ぼう' },
    default: { type: '', compatibility: 'neutral', description: '明るさでチームを照らす', workTip: '計画性も少し意識して' },
  },
  ENFP: {
    ENFP: { type: 'ENFP', compatibility: 'good', description: '創造性の相乗効果', workTip: 'アイデアを実行に移そう' },
    INFP: { type: 'INFP', compatibility: 'excellent', description: '価値観を共有できる', workTip: '互いのアイデアを形に' },
    ENFJ: { type: 'ENFJ', compatibility: 'excellent', description: '情熱的なパートナー', workTip: 'ビジョンを共に実現' },
    ISTJ: { type: 'ISTJ', compatibility: 'challenging', description: '安定志向との違い', workTip: '相手の確実性を活かそう' },
    default: { type: '', compatibility: 'neutral', description: '情熱で人を動かせる', workTip: '現実的な計画も大切に' },
  },
  ENTP: {
    ENTP: { type: 'ENTP', compatibility: 'good', description: '議論が白熱する', workTip: '建設的な結論を出そう' },
    INTP: { type: 'INTP', compatibility: 'excellent', description: '知的探求のパートナー', workTip: '分析を深めつつ行動へ' },
    ENTJ: { type: 'ENTJ', compatibility: 'good', description: '戦略的に協力', workTip: 'アイデアと実行力の融合' },
    ISFJ: { type: 'ISFJ', compatibility: 'challenging', description: '変化への適応の違い', workTip: '相手のペースも尊重して' },
    default: { type: '', compatibility: 'neutral', description: '革新性でチームを刺激', workTip: '周囲への配慮も忘れずに' },
  },
  ESTJ: {
    ESTJ: { type: 'ESTJ', compatibility: 'good', description: '効率的なチーム', workTip: '役割分担を明確に' },
    ISTJ: { type: 'ISTJ', compatibility: 'excellent', description: '信頼できるパートナー', workTip: '責任感で結ばれた関係' },
    ENTJ: { type: 'ENTJ', compatibility: 'good', description: 'リーダー同士の協力', workTip: '互いの領域を尊重して' },
    INFP: { type: 'INFP', compatibility: 'challenging', description: '価値観の違いに注意', workTip: '相手の理想も聞こう' },
    default: { type: '', compatibility: 'neutral', description: '組織力でチームを支える', workTip: '柔軟性も時には大切' },
  },
  ESFJ: {
    ESFJ: { type: 'ESFJ', compatibility: 'good', description: '調和的なチーム', workTip: '互いをサポートし合って' },
    ISFJ: { type: 'ISFJ', compatibility: 'excellent', description: '最高のケアチーム', workTip: '患者さん中心の看護を' },
    ENFJ: { type: 'ENFJ', compatibility: 'good', description: '人を大切にする仲間', workTip: '教育・指導で協力' },
    INTP: { type: 'INTP', compatibility: 'challenging', description: '感情表現の違い', workTip: '論理的意見も受け入れて' },
    default: { type: '', compatibility: 'neutral', description: '気配りでチームを温める', workTip: '自分の意見も大切に' },
  },
  ENFJ: {
    ENFJ: { type: 'ENFJ', compatibility: 'good', description: '情熱が響き合う', workTip: '互いを高め合える関係' },
    INFJ: { type: 'INFJ', compatibility: 'excellent', description: '理想を共に追求', workTip: '深い絆で結ばれた仲間' },
    ESFJ: { type: 'ESFJ', compatibility: 'good', description: '人を育てるチーム', workTip: '教育・指導で協力' },
    ISTP: { type: 'ISTP', compatibility: 'challenging', description: '表現スタイルの違い', workTip: '行動で示す誠意を理解して' },
    default: { type: '', compatibility: 'neutral', description: 'リーダーシップで導ける', workTip: '一人で抱え込まないで' },
  },
  ENTJ: {
    ENTJ: { type: 'ENTJ', compatibility: 'good', description: '戦略的パートナー', workTip: '領域を分けて協力' },
    INTJ: { type: 'INTJ', compatibility: 'excellent', description: 'ビジョンを共有', workTip: '最強の戦略チーム' },
    ESTJ: { type: 'ESTJ', compatibility: 'good', description: '実行力の高いチーム', workTip: '組織を動かす力がある' },
    ISFP: { type: 'ISFP', compatibility: 'challenging', description: 'ペースの違いに注意', workTip: '相手の繊細さを理解しよう' },
    default: { type: '', compatibility: 'neutral', description: '組織を牽引するリーダー', workTip: 'メンバーの気持ちにも配慮を' },
  },
};

// 相性を取得するヘルパー関数
export const getTypeCompatibility = (myType: string, theirType: string): TypeCompatibility => {
  const myCompatibilityMap = TYPE_COMPATIBILITY[myType];
  if (!myCompatibilityMap) {
    return { type: theirType, compatibility: 'neutral', description: '互いを理解し合えば良い関係に', workTip: 'コミュニケーションを大切に' };
  }
  return myCompatibilityMap[theirType] || myCompatibilityMap.default || { 
    type: theirType, 
    compatibility: 'neutral', 
    description: '互いを理解し合えば良い関係に', 
    workTip: 'コミュニケーションを大切に' 
  };
};
